Repository drizzle-team/drizzle-orm, pull requests merged in 2024-11, with the labels that each got.

#3397 OHM static imports checker
  drizzle-kit/.gitignore
  drizzle-kit/imports-checker/analyze.ts
  drizzle-kit/imports-checker/checker.ts
  drizzle-kit/imports-checker/grammar/grammar.ohm
  drizzle-kit/imports-checker/grammar/grammar.ohm-bundle.d.ts
  drizzle-kit/imports-checker/grammar/grammar.ohm-bundle.js
  drizzle-kit/imports-checker/index.ts
  drizzle-kit/package.json
  drizzle-kit/src/@types/utils.ts
  drizzle-kit/src/cli/schema.ts
  drizzle-kit/tests/bin.test.ts
  pnpm-lock.yaml
Labels: ready-to-be-merged

#3328 fix: added commonly used columns to supabase `auth.users` table schema
  drizzle-orm/src/supabase/rls.ts
Labels: ready-to-be-merged

#3200 [drizzle-kit]: Fix breakpoints option cannot be disabled
  drizzle-kit/src/cli/commands/utils.ts
Labels: ready-to-be-merged

#3284 [MySQL] Add unsigned floating point types + Fix unsigned integer type bugs in Kit
  drizzle-kit/src/introspect-mysql.ts
  drizzle-kit/src/serializer/mysqlSerializer.ts
  drizzle-kit/tests/introspect/mysql.test.ts
  drizzle-kit/tests/push/common.ts
  drizzle-kit/tests/push/mysql.test.ts
  drizzle-orm/src/mysql-core/columns/decimal.ts
  drizzle-orm/src/mysql-core/columns/double.ts
  drizzle-orm/src/mysql-core/columns/float.ts
  drizzle-orm/type-tests/mysql/tables.ts
Labels: ready-to-be-merged

#3181 Batch of bugfixes for ORM
  drizzle-orm/src/mysql-core/query-builders/select.ts
  drizzle-orm/src/sqlite-core/columns/blob.ts
  integration-tests/tests/bun/sqlite.test.ts
  integration-tests/tests/mysql/mysql-common.ts
  integration-tests/tests/pg/pg-common.ts
  integration-tests/tests/sqlite/sqlite-common.ts
Labels: ready-to-be-merged

#3141 feat: add tablesFilter to pushSchema api
  drizzle-kit/src/api.ts
  drizzle-kit/src/cli/commands/utils.ts
  drizzle-kit/src/extensions/getTablesFilterByExtensions.ts
Labels: ready-to-be-merged

#2959 Batch of bugfixes for Kit
  drizzle-kit/src/cli/commands/push.ts
  drizzle-kit/src/cli/validations/outputs.ts
  drizzle-kit/src/introspect-mysql.ts
  drizzle-kit/src/introspect-pg.ts
  drizzle-kit/src/introspect-sqlite.ts
  drizzle-kit/src/jsonStatements.ts
  drizzle-kit/src/serializer/mysqlSerializer.ts
  drizzle-kit/src/serializer/pgSchema.ts
  drizzle-kit/src/serializer/pgSerializer.ts
  drizzle-kit/src/serializer/sqliteSerializer.ts
  drizzle-kit/src/snapshotsDiffer.ts
  drizzle-kit/src/sqlgenerator.ts
  drizzle-kit/src/utils.ts
  drizzle-kit/tests/indexes/pg.test.ts
  drizzle-kit/tests/introspect/mysql.test.ts
  drizzle-kit/tests/introspect/pg.test.ts
  drizzle-kit/tests/introspect/sqlite.test.ts
  drizzle-kit/tests/mysql.test.ts
  drizzle-kit/tests/pg-columns.test.ts
  drizzle-kit/tests/pg-enums.test.ts
  drizzle-kit/tests/pg-tables.test.ts
  drizzle-kit/tests/push/common.ts
  drizzle-kit/tests/push/mysql.test.ts
  drizzle-kit/tests/push/pg.test.ts
  drizzle-kit/tests/push/sqlite.test.ts
  drizzle-kit/tests/sqlite-columns.test.ts
  drizzle-kit/tests/sqlite-tables.test.ts
Labels: conflicts

#3172 fix: typo
  drizzle-kit/src/cli/commands/migrate.ts
Labels: ready-to-be-merged

#3030 Fix typo in "your file is ready" messages
  drizzle-kit/src/cli/commands/introspect.ts
Labels: ready-to-be-merged

#2975 [MySQL] Correct $returningId() implementation to correctly store selected fields
  drizzle-orm/src/mysql-core/query-builders/insert.ts
  integration-tests/tests/mysql/mysql-common.ts
Labels: ready-to-be-merged

#2960 revise and proofread project documentation
  CONTRIBUTING.md
  README.md
  docs/custom-types.lite.md
  docs/custom-types.md
  docs/joins.md
  drizzle-kit/README.md
  drizzle-orm/src/sqlite-core/README.md
  examples/mysql-proxy/README.md
  examples/neon-cloudflare/readme.md
  examples/pg-proxy/README.md
  examples/sqlite-proxy/README.md
Labels: ready-to-be-merged

#3197 Fix Drizzle ORM for expo-sqlite
  drizzle-orm/package.json
  drizzle-orm/src/expo-sqlite/driver.ts
  drizzle-orm/src/expo-sqlite/query.ts
  drizzle-orm/src/expo-sqlite/session.ts
  pnpm-lock.yaml
Labels: review-needed

#2963 Support `update ... from` (Pg | SQLite)
  drizzle-orm/src/pg-core/dialect.ts
  drizzle-orm/src/pg-core/query-builders/select.ts
  drizzle-orm/src/pg-core/query-builders/select.types.ts
  drizzle-orm/src/pg-core/query-builders/update.ts
  drizzle-orm/src/sqlite-core/dialect.ts
  drizzle-orm/src/sqlite-core/query-builders/select.ts
  drizzle-orm/src/sqlite-core/query-builders/select.types.ts
  drizzle-orm/src/sqlite-core/query-builders/update.ts
  drizzle-orm/src/utils.ts
  drizzle-orm/type-tests/pg/update.ts
  drizzle-orm/type-tests/sqlite/update.ts
  integration-tests/tests/pg/pg-common.ts
  integration-tests/tests/sqlite/sqlite-common.ts
Labels: conflicts

#2783 Feat: Support `insert into ... select` syntax
  drizzle-orm/src/aws-data-api/pg/driver.ts
  drizzle-orm/src/mysql-core/dialect.ts
  drizzle-orm/src/mysql-core/query-builders/insert.ts
  drizzle-orm/src/pg-core/dialect.ts
  drizzle-orm/src/pg-core/query-builders/insert.ts
  drizzle-orm/src/sqlite-core/dialect.ts
  drizzle-orm/src/sqlite-core/query-builders/insert.ts
  drizzle-orm/type-tests/mysql/insert.ts
  drizzle-orm/type-tests/pg/insert.ts
  drizzle-orm/type-tests/sqlite/insert.ts
  integration-tests/tests/mysql/mysql-common.ts
  integration-tests/tests/pg/pg-common.ts
  integration-tests/tests/sqlite/sqlite-common.ts
  integration-tests/tests/sqlite/sqlite-proxy.test.ts
Labels: conflicts
